import Link from "next/link";
import { MINIMUM_AGE_YEARS } from "@/lib/validation/age";
import { FREE_RESULT_DAYS, PAID_RESULT_DAYS } from "@/lib/evaluation/retention";

/**
 * Terms of service.
 *
 * WRITTEN AGAINST THE CODE, not from a template. Every number on this page is
 * imported from the module that enforces it, so a retention window or an age
 * floor cannot be changed in one place and left stale here — the failure mode
 * of a terms page is that it slowly becomes a description of an older product,
 * and by then it is a document making false statements to customers.
 *
 * PUBLIC AND UNAUTHENTICATED. Somebody deciding whether to sign up has to be
 * able to read this first, and Stripe expects a reachable link.
 *
 * NOT LEGAL ADVICE AND NOT LAWYER-REVIEWED. See the note rendered at the top.
 */
export const metadata = {
  title: "Terms of Service — CourseChart",
};

const UPDATED = "10 September 2026";

export default function TermsPage() {
  return (
    <main className="mx-auto w-full max-w-3xl px-6 py-16">
      <Link
        href="/"
        className="text-sm font-medium text-zinc-500 hover:text-foreground"
      >
        ← CourseChart
      </Link>

      <h1 className="mt-6 text-3xl font-semibold tracking-tight">
        Terms of Service
      </h1>
      <p className="mt-1 text-sm text-zinc-500">Last updated {UPDATED}.</p>

      <div className="mt-8 space-y-8 text-sm leading-6 text-zinc-700 dark:text-zinc-300">
        <Section title="1. What CourseChart is">
          <p>
            CourseChart helps a student build a profile of their grades, tests
            and activities, set target universities, and get AI-generated
            feedback on where they stand. Counselors and tutors can use a
            separate side of the product to work with students who invite them.
          </p>
          <p>
            <Strong>
              It is a planning tool, not an admissions service.
            </Strong>{" "}
            Nothing here is an application, a prediction of an admission
            decision, or advice from a qualified counselor. No university, exam
            board or admissions body is affiliated with CourseChart or endorses
            what it says.
          </p>
        </Section>

        <Section title="2. Who may use it">
          <p>
            You must be at least {MINIMUM_AGE_YEARS} years old to create an
            account. We ask for a date of birth at signup and refuse accounts
            below that age. If you are under the age of majority where you live,
            you should have a parent or guardian&apos;s permission to use this
            service.
          </p>
          <p>
            You are responsible for what happens under your account, including
            keeping your password to yourself. Tell us if you think someone else
            has access to it.
          </p>
        </Section>

        <Section title="3. What the AI produces, and what it is worth">
          <p>
            Evaluations, projections and session prep are generated by a large
            language model from what you enter.{" "}
            <Strong>They can be wrong.</Strong> Scores are calibrated judgements,
            not measurements; requirements and selectivity may be out of date or
            mistaken; and two runs on the same profile may not agree exactly.
          </p>
          <p>
            Check anything that matters against the university&apos;s own
            published information before you act on it. Do not treat output from
            this service as the reason to take or drop a course, sit or skip an
            exam, or apply or not apply somewhere.
          </p>
          <p>
            The service does not state admission probabilities, and is built to
            refuse to. If you ever see output that reads as one, it is a defect
            — please report it.
          </p>
        </Section>

        <Section title="4. Your content is yours">
          <p>
            What you enter — your profile, scores, activities, targets and
            anything you write — remains yours. You give us permission to store
            and process it only to operate the service for you: to run the
            evaluations you ask for, to show your own history back to you, and
            to share it with a counselor you have explicitly invited.
          </p>
          <p>
            We do not sell it, and we do not use it to train models.
          </p>
          <p>
            You can export everything at any time from your settings, and you
            can delete your account, which deletes your records rather than
            hiding them.
          </p>
        </Section>

        <Section title="5. How long written feedback is kept">
          <p>
            To hold less about you over time, the written parts of old
            evaluations are deleted on a schedule: after{" "}
            {FREE_RESULT_DAYS} days on the free plan and after {PAID_RESULT_DAYS}{" "}
            days on a paid plan. The profile snapshot taken at each run goes
            sooner.
          </p>
          <p>
            <Strong>Your scores are not deleted.</Strong> The progress chart is
            meant to cover your whole time at school, so the numbers outlive the
            write-ups they came from. Export anything whose full text you want
            to keep.
          </p>
        </Section>

        <Section title="6. Counselors and student data">
          <p>
            A counselor sees a student only after the student issues an invite
            code and both the student and a parent or guardian agree. Either can
            end that access at any time, and ending it takes effect
            immediately.
          </p>
          <p>
            If you use the counselor side, you agree to use what you see only to
            advise that student, to keep it confidential, and to comply with the
            laws and professional obligations that apply to you — including any
            rules about student records at an institution that employs you.
          </p>
        </Section>

        <Section title="7. Paid plans">
          <p>
            Paid plans are billed monthly in advance through Stripe. We never
            see or store your card details.
          </p>
          <p>
            You can cancel at any time from your billing settings; cancelling
            takes as few clicks as subscribing did. Your plan then runs to the
            end of the period you have already paid for, and is not renewed. We
            do not pro-rate partial months.
          </p>
          <p>
            If we change a price, it applies from your next renewal and not
            retroactively. Nothing you have already run is taken away when a
            plan lapses — you drop back to the free allowance and keep your
            records.
          </p>
        </Section>

        <Section title="8. What you may not do">
          <ul className="list-disc space-y-1 pl-5">
            <li>
              Enter someone else&apos;s personal information without their
              permission, or create an account pretending to be somebody else.
            </li>
            <li>
              Try to access another user&apos;s data, or probe the service for
              ways to do so.
            </li>
            <li>
              Resell or redistribute the output as your own product or advice
              service.
            </li>
            <li>
              Automate access at a volume that degrades the service for other
              people.
            </li>
          </ul>
        </Section>

        <Section title="9. Availability">
          <p>
            The service is provided as it is, without a guarantee that it will
            be available, uninterrupted or error-free. Features may change, and
            plans may be added or retired. If we discontinue something you have
            paid for, we will tell you and refund the unused part of what you
            paid.
          </p>
        </Section>

        <Section title="10. Liability">
          <p>
            To the extent the law allows, CourseChart is not liable for
            indirect or consequential losses — including an admissions outcome,
            a place not offered, or a decision you made after reading something
            here. Our total liability is limited to what you paid us in the
            twelve months before the claim.
          </p>
          <p>
            Nothing here excludes liability that cannot be excluded by law,
            including for death or personal injury caused by negligence, or for
            fraud.
          </p>
        </Section>

        <Section title="11. Ending an account">
          <p>
            You can delete your account at any time from your settings. We may
            suspend or close an account that breaks section 8, or that we are
            required to close by law. If we close yours and you have paid for
            time you have not used, we will refund it unless the closure was for
            a serious breach.
          </p>
        </Section>

        <Section title="12. Changes to these terms">
          <p>
            We may update these terms. If a change materially reduces your
            rights, we will tell you before it takes effect. Continuing to use
            the service after that means you accept the updated terms.
          </p>
        </Section>

        <Section title="13. Contact">
          <p>
            Questions about these terms, or about anything the service has said
            about you, can go to the address on the CourseChart website.
          </p>
        </Section>
      </div>
    </main>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="space-y-3">
      <h2 className="text-lg font-semibold text-zinc-900 dark:text-zinc-100">
        {title}
      </h2>
      {children}
    </section>
  );
}

function Strong({ children }: { children: React.ReactNode }) {
  return (
    <strong className="font-semibold text-zinc-900 dark:text-zinc-100">
      {children}
    </strong>
  );
}
