// Emit the SAME ingest as scripts/ingest-requirements.ts, as a .sql file.
//
//   npx tsx scripts/requirements-to-sql.ts <file.json> > requirements.sql
//
// For when the machine holding the research file cannot reach the database —
// a sandbox that only allows HTTP egress, a laptop behind a firewall, a
// managed Postgres reachable only from its own console. The SQL can then be
// pasted into a provider's web SQL editor or piped through psql from anywhere.
//
// It reuses validateRecord and matchKey rather than reimplementing them, so a
// record that would be rejected by the real ingest is rejected here too. The
// only difference is the destination: INSERT text on stdout instead of a
// Prisma write. If those two ever disagree, this file is the bug.
//
// Commentary goes to stderr so `> file.sql` yields something executable.
import { readFileSync } from "node:fs";
import { randomUUID } from "node:crypto";
import { validateRecord } from "../lib/validation/course-requirements";
import { isUsableKey, matchKey } from "../lib/requirements/match";

const args = process.argv.slice(2);
const path = args.find((a) => !a.startsWith("--"));

if (!path) {
  console.error("Usage: npx tsx scripts/requirements-to-sql.ts <file.json>");
  process.exit(1);
}

/**
 * A Postgres string literal.
 *
 * Doubling single quotes is the whole escape under standard_conforming_strings,
 * which has been the default since Postgres 9.1 — so backslashes are literal
 * and need no handling. E'' syntax would need the opposite. The generated file
 * sets the setting explicitly rather than assuming the session default.
 */
function lit(value: string | null | undefined): string {
  if (value == null) return "NULL";
  return `'${value.replace(/'/g, "''")}'`;
}

function num(value: number | null | undefined): string {
  return value == null ? "NULL" : String(value);
}

function readRecords(file: string): unknown[] {
  const parsed = JSON.parse(readFileSync(file, "utf8"));
  if (Array.isArray(parsed)) return parsed;
  if (parsed && typeof parsed === "object") {
    for (const value of Object.values(parsed)) {
      if (Array.isArray(value)) return value;
    }
  }
  console.error(`${file} contains no array of records.`);
  process.exit(1);
}

const records = readRecords(path);
let accepted = 0;
let rejected = 0;

const out: string[] = [];
out.push("-- Researched course entry requirements.");
out.push(`-- Generated from ${path}`);
out.push("-- Safe to re-run: each row upserts on matchKey.");
out.push("SET standard_conforming_strings = on;");
out.push("BEGIN;");

for (const raw of records) {
  const outcome = validateRecord(raw);
  if (!outcome.ok) {
    rejected += 1;
    continue;
  }
  const r = outcome.record;
  const key = matchKey(r);
  if (!isUsableKey(key)) {
    rejected += 1;
    continue;
  }
  accepted += 1;

  const values = [
    lit(randomUUID()),
    lit(key),
    lit(r.university),
    lit(r.country),
    lit(r.course),
    String(r.cycleYear),
    r.stale ? "true" : "false",
    `'${r.gatheredOn}T00:00:00Z'::timestamp`,
    lit(r.primarySourceUrl),
    lit(JSON.stringify(r.requirements)),
    num(r.acceptanceRate?.percent),
    lit(r.acceptanceRate?.scope),
    lit(r.acceptanceRate?.sourceUrl),
  ].join(", ");

  // Upsert, matching the real ingest: a refresh of the same course replaces
  // the old row rather than accumulating a second one nothing can choose
  // between. "id" is kept on conflict so existing references stay valid.
  //
  // "updatedAt" is set explicitly because Prisma's @updatedAt is generated by
  // the CLIENT, not the database — the column is NOT NULL with no default, so
  // SQL that omits it fails on the first row. (It did.)
  out.push(
    `INSERT INTO "CourseRequirement" ` +
      `("id", "matchKey", "university", "country", "course", "cycleYear", "stale", ` +
      `"gatheredOn", "primarySourceUrl", "requirementsJson", ` +
      `"acceptanceRatePercent", "acceptanceRateScope", "acceptanceRateSourceUrl", ` +
      `"updatedAt") ` +
      `VALUES (${values}, NOW()) ` +
      `ON CONFLICT ("matchKey") DO UPDATE SET ` +
      `"university" = EXCLUDED."university", "country" = EXCLUDED."country", ` +
      `"course" = EXCLUDED."course", "cycleYear" = EXCLUDED."cycleYear", ` +
      `"stale" = EXCLUDED."stale", "gatheredOn" = EXCLUDED."gatheredOn", ` +
      `"primarySourceUrl" = EXCLUDED."primarySourceUrl", ` +
      `"requirementsJson" = EXCLUDED."requirementsJson", ` +
      `"acceptanceRatePercent" = EXCLUDED."acceptanceRatePercent", ` +
      `"acceptanceRateScope" = EXCLUDED."acceptanceRateScope", ` +
      `"acceptanceRateSourceUrl" = EXCLUDED."acceptanceRateSourceUrl", ` +
      `"updatedAt" = NOW();`,
  );
}

out.push("COMMIT;");
out.push(`-- ${accepted} row(s) upserted, ${rejected} record(s) rejected.`);

console.log(out.join("\n"));
console.error(`\n  accepted : ${accepted}`);
console.error(`  rejected : ${rejected}\n`);
